env:
  browser: true
  es6: true
  node: true
  jest/globals: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2017
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - jest
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  react/jsx-uses-vars:
    - error
  react/jsx-uses-react:
    - error
